# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_first.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 360)
        Dialog.setMinimumSize(QtCore.QSize(480, 360))
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(236, 243, 251);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setContentsMargins(-1, 10, -1, 20)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_title = QtWidgets.QFrame(Dialog)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 84))
        self.frame_title.setMaximumSize(QtCore.QSize(600, 84))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.frame_title.setFont(font)
        self.frame_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_title.setStyleSheet("#label_01{\n"
"    color: #064993;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_title = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_title.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_title.setSpacing(6)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.label_00 = QtWidgets.QLabel(self.frame_title)
        self.label_00.setMinimumSize(QtCore.QSize(317, 55))
        self.label_00.setMaximumSize(QtCore.QSize(317, 55))
        self.label_00.setText("")
        self.label_00.setPixmap(QtGui.QPixmap(":/images/image_title.tif"))
        self.label_00.setScaledContents(True)
        self.label_00.setAlignment(QtCore.Qt.AlignCenter)
        self.label_00.setObjectName("label_00")
        self.verticalLayout_title.addWidget(self.label_00, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_01 = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_01.setFont(font)
        self.label_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_01.setObjectName("label_01")
        self.verticalLayout_title.addWidget(self.label_01)
        self.verticalLayout_3.addWidget(self.frame_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_choose = QtWidgets.QFrame(Dialog)
        self.frame_choose.setMinimumSize(QtCore.QSize(0, 240))
        self.frame_choose.setMaximumSize(QtCore.QSize(600, 240))
        self.frame_choose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_choose.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_choose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choose.setObjectName("frame_choose")
        self.horizontalLayout_choose = QtWidgets.QHBoxLayout(self.frame_choose)
        self.horizontalLayout_choose.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_choose.setSpacing(10)
        self.horizontalLayout_choose.setObjectName("horizontalLayout_choose")
        self.frame_small = QtWidgets.QFrame(self.frame_choose)
        self.frame_small.setMinimumSize(QtCore.QSize(220, 220))
        self.frame_small.setMaximumSize(QtCore.QSize(220, 220))
        self.frame_small.setStyleSheet("QFrame{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"}")
        self.frame_small.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_small.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_small.setObjectName("frame_small")
        self.verticalLayout_small = QtWidgets.QVBoxLayout(self.frame_small)
        self.verticalLayout_small.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_small.setSpacing(0)
        self.verticalLayout_small.setObjectName("verticalLayout_small")
        self.frame_10 = QtWidgets.QFrame(self.frame_small)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setMinimumSize(QtCore.QSize(220, 94))
        self.label_10.setMaximumSize(QtCore.QSize(220, 94))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/images/image_small.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.verticalLayout_small.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_small)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 64))
        self.frame_11.setStyleSheet("#label_11{\n"
"    color: #333333;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"#label_12{\n"
"    color: #FB824F;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_11.setContentsMargins(24, 10, 24, 10)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.verticalLayout_small.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_small)
        self.frame_12.setStyleSheet("QPushButton{\n"
"    background: #0757AD;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    color: #FFFFFF;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_12.setContentsMargins(24, 8, 24, 8)
        self.horizontalLayout_12.setSpacing(8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_1.setMinimumSize(QtCore.QSize(108, 27))
        self.pushButton_1.setMaximumSize(QtCore.QSize(108, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(8)
        font.setItalic(False)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_12.addWidget(self.pushButton_1, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_small.addWidget(self.frame_12)
        self.horizontalLayout_choose.addWidget(self.frame_small)
        self.frame_large = QtWidgets.QFrame(self.frame_choose)
        self.frame_large.setMinimumSize(QtCore.QSize(220, 220))
        self.frame_large.setMaximumSize(QtCore.QSize(220, 220))
        self.frame_large.setStyleSheet("QFrame{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"}")
        self.frame_large.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_large.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_large.setObjectName("frame_large")
        self.verticalLayout_large = QtWidgets.QVBoxLayout(self.frame_large)
        self.verticalLayout_large.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_large.setSpacing(0)
        self.verticalLayout_large.setObjectName("verticalLayout_large")
        self.frame_20 = QtWidgets.QFrame(self.frame_large)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setMinimumSize(QtCore.QSize(220, 94))
        self.label_20.setMaximumSize(QtCore.QSize(220, 94))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/images/image_large.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.verticalLayout_large.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_large)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 64))
        self.frame_21.setStyleSheet("#label_21{\n"
"    color: #333333;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"#label_22{\n"
"    color: #FB824F;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_21.setContentsMargins(24, 10, 24, 10)
        self.verticalLayout_21.setSpacing(10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_21 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_21.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_21.addWidget(self.label_22)
        self.verticalLayout_large.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_large)
        self.frame_22.setStyleSheet("QPushButton{\n"
"    background: #0757AD;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    color: #FFFFFF;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_22.setContentsMargins(24, 8, 24, 8)
        self.horizontalLayout_22.setSpacing(8)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_2.setMinimumSize(QtCore.QSize(108, 27))
        self.pushButton_2.setMaximumSize(QtCore.QSize(108, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(8)
        font.setItalic(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_22.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_large.addWidget(self.frame_22)
        self.horizontalLayout_choose.addWidget(self.frame_large)
        self.verticalLayout_3.addWidget(self.frame_choose, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "北京卫星环境工程研究所 结构应力特征辨识"))
        self.label_01.setText(_translate("Dialog", "结构应力特征辨识"))
        self.label_11.setText(_translate("Dialog", "小型零件"))
        self.label_12.setText(_translate("Dialog", "危险位置应力应变辨识"))
        self.pushButton_1.setText(_translate("Dialog", "点击进入"))
        self.label_21.setText(_translate("Dialog", "大型零件"))
        self.label_22.setText(_translate("Dialog", "危险位置应力应变辨识"))
        self.pushButton_2.setText(_translate("Dialog", "点击进入"))
import res_rc
