# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_small.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(236, 243, 251);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(6, 10, 6, 10)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_up = QtWidgets.QFrame(Dialog)
        self.frame_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_up.setObjectName("frame_up")
        self.horizontalLayout_up = QtWidgets.QHBoxLayout(self.frame_up)
        self.horizontalLayout_up.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_up.setObjectName("horizontalLayout_up")
        self.frame_left = QtWidgets.QFrame(self.frame_up)
        self.frame_left.setEnabled(True)
        self.frame_left.setMaximumSize(QtCore.QSize(16777215, 540))
        self.frame_left.setStyleSheet("#frame_left{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_left = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_left.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_left.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_left.setSpacing(6)
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.frame_title = QtWidgets.QFrame(self.frame_left)
        self.frame_title.setStyleSheet("#frame_title{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_title = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_title.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_title.setObjectName("horizontalLayout_title")
        self.label = QtWidgets.QLabel(self.frame_title)
        self.label.setMaximumSize(QtCore.QSize(173, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/image_title.tif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_title.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_title.addItem(spacerItem)
        self.pushButton_00 = QtWidgets.QPushButton(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_00.setFont(font)
        self.pushButton_00.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon_about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_00.setIcon(icon1)
        self.pushButton_00.setObjectName("pushButton_00")
        self.horizontalLayout_title.addWidget(self.pushButton_00)
        self.verticalLayout_left.addWidget(self.frame_title, 0, QtCore.Qt.AlignVCenter)
        self.frame_clip = QtWidgets.QFrame(self.frame_left)
        self.frame_clip.setMinimumSize(QtCore.QSize(0, 194))
        self.frame_clip.setStyleSheet("#frame_clip{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_clip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clip.setObjectName("frame_clip")
        self.verticalLayout_clip = QtWidgets.QVBoxLayout(self.frame_clip)
        self.verticalLayout_clip.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_clip.setSpacing(0)
        self.verticalLayout_clip.setObjectName("verticalLayout_clip")
        self.frame_clip_title = QtWidgets.QFrame(self.frame_clip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_clip_title.sizePolicy().hasHeightForWidth())
        self.frame_clip_title.setSizePolicy(sizePolicy)
        self.frame_clip_title.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_clip_title.setStyleSheet("#frame_clip_title{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"#frame_10{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QRadioButton{\n"
"    border: none;\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"}")
        self.frame_clip_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clip_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clip_title.setObjectName("frame_clip_title")
        self.horizontalLayout_clip_title = QtWidgets.QHBoxLayout(self.frame_clip_title)
        self.horizontalLayout_clip_title.setContentsMargins(6, 0, 10, 0)
        self.horizontalLayout_clip_title.setSpacing(6)
        self.horizontalLayout_clip_title.setObjectName("horizontalLayout_clip_title")
        self.frame_10 = QtWidgets.QFrame(self.frame_clip_title)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setMinimumSize(QtCore.QSize(15, 15))
        self.label_10.setMaximumSize(QtCore.QSize(15, 15))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/icons/icon_01.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.label_100 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.horizontalLayout_10.addWidget(self.label_100)
        self.horizontalLayout_clip_title.addWidget(self.frame_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_clip_title.addItem(spacerItem1)
        self.radioButton = QtWidgets.QRadioButton(self.frame_clip_title)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_clip_title.addWidget(self.radioButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_clip_title.addItem(spacerItem2)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_clip_title)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_clip_title.addWidget(self.pushButton_10)
        self.verticalLayout_clip.addWidget(self.frame_clip_title)
        self.frame_clip_input_1 = QtWidgets.QFrame(self.frame_clip)
        self.frame_clip_input_1.setStyleSheet("QPushButton{\n"
"    width: 50px;\n"
"    height: 20px;\n"
"    background: #FFFFFF;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DDDDDD;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DDDDDD;\n"
"}")
        self.frame_clip_input_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clip_input_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clip_input_1.setObjectName("frame_clip_input_1")
        self.horizontalLayout_clip_input_1 = QtWidgets.QHBoxLayout(self.frame_clip_input_1)
        self.horizontalLayout_clip_input_1.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_clip_input_1.setSpacing(6)
        self.horizontalLayout_clip_input_1.setObjectName("horizontalLayout_clip_input_1")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_clip_input_1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setDefault(False)
        self.pushButton_11.setFlat(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_clip_input_1.addWidget(self.pushButton_11)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_clip_input_1)
        self.lineEdit_11.setStyleSheet("QlineEdit {\n"
"    background-color: rgb(236, 243, 251);\n"
"    selection-color: rgb(236, 243, 251);\n"
"}")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_clip_input_1.addWidget(self.lineEdit_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_clip_input_1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_clip_input_1.addWidget(self.pushButton_12)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_clip_input_1)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_clip_input_1.addWidget(self.lineEdit_12)
        self.verticalLayout_clip.addWidget(self.frame_clip_input_1)
        self.frame_clip_input_2 = QtWidgets.QFrame(self.frame_clip)
        self.frame_clip_input_2.setStyleSheet("QPushButton{\n"
"    width: 50px;\n"
"    height: 20px;\n"
"    background: #FFFFFF;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DDDDDD;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DDDDDD;\n"
"}")
        self.frame_clip_input_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clip_input_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clip_input_2.setObjectName("frame_clip_input_2")
        self.horizontalLayout_clip_input_2 = QtWidgets.QHBoxLayout(self.frame_clip_input_2)
        self.horizontalLayout_clip_input_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_clip_input_2.setSpacing(6)
        self.horizontalLayout_clip_input_2.setObjectName("horizontalLayout_clip_input_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_clip_input_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_clip_input_2.addWidget(self.pushButton_13)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_clip_input_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_clip_input_2.addWidget(self.lineEdit_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_clip_input_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_clip_input_2.addWidget(self.pushButton_14)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_clip_input_2)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_clip_input_2.addWidget(self.lineEdit_14)
        self.verticalLayout_clip.addWidget(self.frame_clip_input_2)
        self.frame_clip_input_3 = QtWidgets.QFrame(self.frame_clip)
        self.frame_clip_input_3.setStyleSheet("QPushButton{\n"
"    width: 50px;\n"
"    height: 20px;\n"
"    background: #FFFFFF;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DDDDDD;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DDDDDD;\n"
"}")
        self.frame_clip_input_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clip_input_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clip_input_3.setObjectName("frame_clip_input_3")
        self.horizontalLayout_clip_input_3 = QtWidgets.QHBoxLayout(self.frame_clip_input_3)
        self.horizontalLayout_clip_input_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_clip_input_3.setSpacing(6)
        self.horizontalLayout_clip_input_3.setObjectName("horizontalLayout_clip_input_3")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_clip_input_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_clip_input_3.addWidget(self.pushButton_15)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_clip_input_3)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_clip_input_3.addWidget(self.lineEdit_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_clip_input_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_clip_input_3.addWidget(self.pushButton_16)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_clip_input_3)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_clip_input_3.addWidget(self.lineEdit_16)
        self.verticalLayout_clip.addWidget(self.frame_clip_input_3)
        self.frame_clip_file = QtWidgets.QFrame(self.frame_clip)
        self.frame_clip_file.setStyleSheet("QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QPushButton {\n"
"    height: 20px;\n"
"    background: #00337E;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_clip_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clip_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clip_file.setObjectName("frame_clip_file")
        self.horizontalLayout_clip_file = QtWidgets.QHBoxLayout(self.frame_clip_file)
        self.horizontalLayout_clip_file.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_clip_file.setSpacing(6)
        self.horizontalLayout_clip_file.setObjectName("horizontalLayout_clip_file")
        self.label_101 = QtWidgets.QLabel(self.frame_clip_file)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.horizontalLayout_clip_file.addWidget(self.label_101)
        spacerItem3 = QtWidgets.QSpacerItem(114, 14, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_clip_file.addItem(spacerItem3)
        self.pushButton_101 = QtWidgets.QPushButton(self.frame_clip_file)
        self.pushButton_101.setMinimumSize(QtCore.QSize(108, 20))
        self.pushButton_101.setMaximumSize(QtCore.QSize(108, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_101.setFont(font)
        self.pushButton_101.setStyleSheet("")
        self.pushButton_101.setObjectName("pushButton_101")
        self.horizontalLayout_clip_file.addWidget(self.pushButton_101)
        self.verticalLayout_clip.addWidget(self.frame_clip_file)
        self.frame_clip_file_read = QtWidgets.QFrame(self.frame_clip)
        self.frame_clip_file_read.setStyleSheet("QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QLineEdit{\n"
"    width: 309px;\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_clip_file_read.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clip_file_read.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clip_file_read.setObjectName("frame_clip_file_read")
        self.horizontalLayout_clip_file_read = QtWidgets.QHBoxLayout(self.frame_clip_file_read)
        self.horizontalLayout_clip_file_read.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_clip_file_read.setSpacing(6)
        self.horizontalLayout_clip_file_read.setObjectName("horizontalLayout_clip_file_read")
        self.lineEdit_102 = QtWidgets.QLineEdit(self.frame_clip_file_read)
        self.lineEdit_102.setObjectName("lineEdit_102")
        self.horizontalLayout_clip_file_read.addWidget(self.lineEdit_102)
        self.pushButton_102 = QtWidgets.QPushButton(self.frame_clip_file_read)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_102.setFont(font)
        self.pushButton_102.setObjectName("pushButton_102")
        self.horizontalLayout_clip_file_read.addWidget(self.pushButton_102)
        self.verticalLayout_clip.addWidget(self.frame_clip_file_read)
        self.frame_clip_output = QtWidgets.QFrame(self.frame_clip)
        self.frame_clip_output.setStyleSheet("QFrame{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDD;\n"
"}")
        self.frame_clip_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clip_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clip_output.setObjectName("frame_clip_output")
        self.horizontalLayout_clip_output = QtWidgets.QHBoxLayout(self.frame_clip_output)
        self.horizontalLayout_clip_output.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_clip_output.setSpacing(10)
        self.horizontalLayout_clip_output.setObjectName("horizontalLayout_clip_output")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_clip_output.addItem(spacerItem4)
        self.pushButton_103 = QtWidgets.QPushButton(self.frame_clip_output)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.pushButton_103.setFont(font)
        self.pushButton_103.setObjectName("pushButton_103")
        self.horizontalLayout_clip_output.addWidget(self.pushButton_103)
        self.pushButton_100 = QtWidgets.QPushButton(self.frame_clip_output)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.pushButton_100.setFont(font)
        self.pushButton_100.setObjectName("pushButton_100")
        self.horizontalLayout_clip_output.addWidget(self.pushButton_100)
        self.verticalLayout_clip.addWidget(self.frame_clip_output)
        self.frame_clip_file.raise_()
        self.frame_clip_title.raise_()
        self.frame_clip_input_1.raise_()
        self.frame_clip_input_3.raise_()
        self.frame_clip_file_read.raise_()
        self.frame_clip_output.raise_()
        self.frame_clip_input_2.raise_()
        self.verticalLayout_left.addWidget(self.frame_clip, 0, QtCore.Qt.AlignVCenter)
        self.frame_fm = QtWidgets.QFrame(self.frame_left)
        self.frame_fm.setMinimumSize(QtCore.QSize(0, 194))
        self.frame_fm.setStyleSheet("#frame_fm{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_fm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fm.setObjectName("frame_fm")
        self.verticalLayout_fm = QtWidgets.QVBoxLayout(self.frame_fm)
        self.verticalLayout_fm.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_fm.setSpacing(0)
        self.verticalLayout_fm.setObjectName("verticalLayout_fm")
        self.frame_fm_title = QtWidgets.QFrame(self.frame_fm)
        self.frame_fm_title.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_fm_title.setStyleSheet("#frame_fm_title{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"#frame_20{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QLabel {\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}")
        self.frame_fm_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fm_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fm_title.setObjectName("frame_fm_title")
        self.horizontalLayout_fm_title = QtWidgets.QHBoxLayout(self.frame_fm_title)
        self.horizontalLayout_fm_title.setContentsMargins(6, 0, 10, 0)
        self.horizontalLayout_fm_title.setSpacing(6)
        self.horizontalLayout_fm_title.setObjectName("horizontalLayout_fm_title")
        self.frame_20 = QtWidgets.QFrame(self.frame_fm_title)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setMinimumSize(QtCore.QSize(15, 15))
        self.label_20.setMaximumSize(QtCore.QSize(15, 15))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/icons/icon_02.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.label_200 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_200.setFont(font)
        self.label_200.setObjectName("label_200")
        self.horizontalLayout_20.addWidget(self.label_200)
        self.horizontalLayout_fm_title.addWidget(self.frame_20)
        spacerItem5 = QtWidgets.QSpacerItem(202, 6, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_fm_title.addItem(spacerItem5)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_fm_title)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setText("")
        self.pushButton_20.setIcon(icon1)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_fm_title.addWidget(self.pushButton_20)
        self.verticalLayout_fm.addWidget(self.frame_fm_title)
        self.frame_fm_input_1 = QtWidgets.QFrame(self.frame_fm)
        self.frame_fm_input_1.setStyleSheet("QLabel{\n"
"    font-weight: 500;\n"
"    font-size: 12px;\n"
"    color: #333333;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DDDDDD;\n"
"}")
        self.frame_fm_input_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fm_input_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fm_input_1.setObjectName("frame_fm_input_1")
        self.horizontalLayout_fm_input_1 = QtWidgets.QHBoxLayout(self.frame_fm_input_1)
        self.horizontalLayout_fm_input_1.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_fm_input_1.setSpacing(6)
        self.horizontalLayout_fm_input_1.setObjectName("horizontalLayout_fm_input_1")
        self.label_21 = QtWidgets.QLabel(self.frame_fm_input_1)
        self.label_21.setMinimumSize(QtCore.QSize(36, 0))
        self.label_21.setMaximumSize(QtCore.QSize(36, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_fm_input_1.addWidget(self.label_21)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_fm_input_1)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_fm_input_1.addWidget(self.lineEdit_21)
        self.label_24 = QtWidgets.QLabel(self.frame_fm_input_1)
        self.label_24.setMinimumSize(QtCore.QSize(52, 0))
        self.label_24.setMaximumSize(QtCore.QSize(52, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_fm_input_1.addWidget(self.label_24)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_fm_input_1)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_fm_input_1.addWidget(self.lineEdit_24)
        self.verticalLayout_fm.addWidget(self.frame_fm_input_1)
        self.frame_fm_input_2 = QtWidgets.QFrame(self.frame_fm)
        self.frame_fm_input_2.setStyleSheet("QLabel{\n"
"    font-weight: 500;\n"
"    font-size: 12px;\n"
"    color: #333333;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DDDDDD;\n"
"}")
        self.frame_fm_input_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fm_input_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fm_input_2.setObjectName("frame_fm_input_2")
        self.horizontalLayout_fm_input_2 = QtWidgets.QHBoxLayout(self.frame_fm_input_2)
        self.horizontalLayout_fm_input_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_fm_input_2.setSpacing(6)
        self.horizontalLayout_fm_input_2.setObjectName("horizontalLayout_fm_input_2")
        self.label_22 = QtWidgets.QLabel(self.frame_fm_input_2)
        self.label_22.setMinimumSize(QtCore.QSize(36, 0))
        self.label_22.setMaximumSize(QtCore.QSize(36, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_fm_input_2.addWidget(self.label_22)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_fm_input_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_fm_input_2.addWidget(self.lineEdit_22)
        self.label_25 = QtWidgets.QLabel(self.frame_fm_input_2)
        self.label_25.setMinimumSize(QtCore.QSize(52, 0))
        self.label_25.setMaximumSize(QtCore.QSize(52, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_fm_input_2.addWidget(self.label_25)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_fm_input_2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_fm_input_2.addWidget(self.lineEdit_25)
        self.verticalLayout_fm.addWidget(self.frame_fm_input_2)
        self.frame_fm_input_3 = QtWidgets.QFrame(self.frame_fm)
        self.frame_fm_input_3.setStyleSheet("QLabel{\n"
"    font-weight: 500;\n"
"    font-size: 12px;\n"
"    color: #333333;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DDDDDD;\n"
"}")
        self.frame_fm_input_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fm_input_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fm_input_3.setObjectName("frame_fm_input_3")
        self.horizontalLayout_fm_input_3 = QtWidgets.QHBoxLayout(self.frame_fm_input_3)
        self.horizontalLayout_fm_input_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_fm_input_3.setSpacing(6)
        self.horizontalLayout_fm_input_3.setObjectName("horizontalLayout_fm_input_3")
        self.label_23 = QtWidgets.QLabel(self.frame_fm_input_3)
        self.label_23.setMinimumSize(QtCore.QSize(36, 0))
        self.label_23.setMaximumSize(QtCore.QSize(36, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_fm_input_3.addWidget(self.label_23)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_fm_input_3)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_fm_input_3.addWidget(self.lineEdit_23)
        self.label_26 = QtWidgets.QLabel(self.frame_fm_input_3)
        self.label_26.setMinimumSize(QtCore.QSize(52, 0))
        self.label_26.setMaximumSize(QtCore.QSize(52, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_fm_input_3.addWidget(self.label_26)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_fm_input_3)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_fm_input_3.addWidget(self.lineEdit_26)
        self.verticalLayout_fm.addWidget(self.frame_fm_input_3)
        self.frame_fm_file = QtWidgets.QFrame(self.frame_fm)
        self.frame_fm_file.setStyleSheet("QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QPushButton {\n"
"    height: 20px;\n"
"    background: #00337E;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_fm_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fm_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fm_file.setObjectName("frame_fm_file")
        self.horizontalLayout_fm_file = QtWidgets.QHBoxLayout(self.frame_fm_file)
        self.horizontalLayout_fm_file.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_fm_file.setSpacing(6)
        self.horizontalLayout_fm_file.setObjectName("horizontalLayout_fm_file")
        self.label_201 = QtWidgets.QLabel(self.frame_fm_file)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_201.setFont(font)
        self.label_201.setObjectName("label_201")
        self.horizontalLayout_fm_file.addWidget(self.label_201)
        spacerItem6 = QtWidgets.QSpacerItem(90, 6, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_fm_file.addItem(spacerItem6)
        self.pushButton_201 = QtWidgets.QPushButton(self.frame_fm_file)
        self.pushButton_201.setMinimumSize(QtCore.QSize(108, 20))
        self.pushButton_201.setMaximumSize(QtCore.QSize(108, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_201.setFont(font)
        self.pushButton_201.setStyleSheet("")
        self.pushButton_201.setObjectName("pushButton_201")
        self.horizontalLayout_fm_file.addWidget(self.pushButton_201)
        self.verticalLayout_fm.addWidget(self.frame_fm_file)
        self.frame_fm_file_read = QtWidgets.QFrame(self.frame_fm)
        self.frame_fm_file_read.setStyleSheet("QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_fm_file_read.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fm_file_read.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fm_file_read.setObjectName("frame_fm_file_read")
        self.horizontalLayout_fm_file_read = QtWidgets.QHBoxLayout(self.frame_fm_file_read)
        self.horizontalLayout_fm_file_read.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_fm_file_read.setSpacing(6)
        self.horizontalLayout_fm_file_read.setObjectName("horizontalLayout_fm_file_read")
        self.lineEdit_202 = QtWidgets.QLineEdit(self.frame_fm_file_read)
        self.lineEdit_202.setObjectName("lineEdit_202")
        self.horizontalLayout_fm_file_read.addWidget(self.lineEdit_202)
        self.pushButton_202 = QtWidgets.QPushButton(self.frame_fm_file_read)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.pushButton_202.setFont(font)
        self.pushButton_202.setObjectName("pushButton_202")
        self.horizontalLayout_fm_file_read.addWidget(self.pushButton_202)
        self.verticalLayout_fm.addWidget(self.frame_fm_file_read)
        self.frame_fm_output = QtWidgets.QFrame(self.frame_fm)
        self.frame_fm_output.setStyleSheet("QFrame{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDD;\n"
"}")
        self.frame_fm_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fm_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fm_output.setObjectName("frame_fm_output")
        self.horizontalLayout_fm_output = QtWidgets.QHBoxLayout(self.frame_fm_output)
        self.horizontalLayout_fm_output.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_fm_output.setSpacing(10)
        self.horizontalLayout_fm_output.setObjectName("horizontalLayout_fm_output")
        spacerItem7 = QtWidgets.QSpacerItem(222, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_fm_output.addItem(spacerItem7)
        self.pushButton_203 = QtWidgets.QPushButton(self.frame_fm_output)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.pushButton_203.setFont(font)
        self.pushButton_203.setObjectName("pushButton_203")
        self.horizontalLayout_fm_output.addWidget(self.pushButton_203)
        self.pushButton_200 = QtWidgets.QPushButton(self.frame_fm_output)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.pushButton_200.setFont(font)
        self.pushButton_200.setObjectName("pushButton_200")
        self.horizontalLayout_fm_output.addWidget(self.pushButton_200)
        self.verticalLayout_fm.addWidget(self.frame_fm_output)
        self.verticalLayout_left.addWidget(self.frame_fm, 0, QtCore.Qt.AlignVCenter)
        self.frame_ans = QtWidgets.QFrame(self.frame_left)
        self.frame_ans.setMinimumSize(QtCore.QSize(0, 84))
        self.frame_ans.setStyleSheet("#frame_ans{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_ans.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ans.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ans.setObjectName("frame_ans")
        self.verticalLayout_ans = QtWidgets.QVBoxLayout(self.frame_ans)
        self.verticalLayout_ans.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_ans.setSpacing(0)
        self.verticalLayout_ans.setObjectName("verticalLayout_ans")
        self.frame_ans_title = QtWidgets.QFrame(self.frame_ans)
        self.frame_ans_title.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_ans_title.setStyleSheet("#frame_ans_title{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"#frame_30{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QLabel {\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}")
        self.frame_ans_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ans_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ans_title.setObjectName("frame_ans_title")
        self.horizontalLayout_ans_title = QtWidgets.QHBoxLayout(self.frame_ans_title)
        self.horizontalLayout_ans_title.setContentsMargins(6, 0, 10, 0)
        self.horizontalLayout_ans_title.setSpacing(6)
        self.horizontalLayout_ans_title.setObjectName("horizontalLayout_ans_title")
        self.frame_30 = QtWidgets.QFrame(self.frame_ans_title)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(6)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_30 = QtWidgets.QLabel(self.frame_30)
        self.label_30.setMinimumSize(QtCore.QSize(15, 15))
        self.label_30.setMaximumSize(QtCore.QSize(15, 15))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap(":/icons/icon_save.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_30.addWidget(self.label_30)
        self.label_300 = QtWidgets.QLabel(self.frame_30)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_300.setFont(font)
        self.label_300.setObjectName("label_300")
        self.horizontalLayout_30.addWidget(self.label_300)
        self.horizontalLayout_ans_title.addWidget(self.frame_30)
        spacerItem8 = QtWidgets.QSpacerItem(202, 6, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_ans_title.addItem(spacerItem8)
        self.pushButton_30 = QtWidgets.QPushButton(self.frame_ans_title)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setText("")
        self.pushButton_30.setIcon(icon1)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_ans_title.addWidget(self.pushButton_30)
        self.verticalLayout_ans.addWidget(self.frame_ans_title)
        self.frame_ans_file = QtWidgets.QFrame(self.frame_ans)
        self.frame_ans_file.setStyleSheet("QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QPushButton {\n"
"    height: 20px;\n"
"    background: #00337E;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_ans_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ans_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ans_file.setObjectName("frame_ans_file")
        self.horizontalLayout_ans_file = QtWidgets.QHBoxLayout(self.frame_ans_file)
        self.horizontalLayout_ans_file.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_ans_file.setSpacing(6)
        self.horizontalLayout_ans_file.setObjectName("horizontalLayout_ans_file")
        self.label_301 = QtWidgets.QLabel(self.frame_ans_file)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_301.setFont(font)
        self.label_301.setObjectName("label_301")
        self.horizontalLayout_ans_file.addWidget(self.label_301)
        spacerItem9 = QtWidgets.QSpacerItem(90, 6, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_ans_file.addItem(spacerItem9)
        self.pushButton_301 = QtWidgets.QPushButton(self.frame_ans_file)
        self.pushButton_301.setMinimumSize(QtCore.QSize(108, 20))
        self.pushButton_301.setMaximumSize(QtCore.QSize(108, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_301.setFont(font)
        self.pushButton_301.setStyleSheet("")
        self.pushButton_301.setObjectName("pushButton_301")
        self.horizontalLayout_ans_file.addWidget(self.pushButton_301)
        self.verticalLayout_ans.addWidget(self.frame_ans_file)
        self.frame_ans_file_write = QtWidgets.QFrame(self.frame_ans)
        self.frame_ans_file_write.setStyleSheet("QFrame{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_ans_file_write.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ans_file_write.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ans_file_write.setObjectName("frame_ans_file_write")
        self.horizontalLayout_ans_file_write = QtWidgets.QHBoxLayout(self.frame_ans_file_write)
        self.horizontalLayout_ans_file_write.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_ans_file_write.setSpacing(6)
        self.horizontalLayout_ans_file_write.setObjectName("horizontalLayout_ans_file_write")
        self.lineEdit_302 = QtWidgets.QLineEdit(self.frame_ans_file_write)
        self.lineEdit_302.setObjectName("lineEdit_302")
        self.horizontalLayout_ans_file_write.addWidget(self.lineEdit_302)
        self.label_31 = QtWidgets.QLabel(self.frame_ans_file_write)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_ans_file_write.addWidget(self.label_31)
        self.lineEdit_303 = QtWidgets.QLineEdit(self.frame_ans_file_write)
        self.lineEdit_303.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_303.setObjectName("lineEdit_303")
        self.horizontalLayout_ans_file_write.addWidget(self.lineEdit_303)
        self.label_32 = QtWidgets.QLabel(self.frame_ans_file_write)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_ans_file_write.addWidget(self.label_32)
        self.pushButton_302 = QtWidgets.QPushButton(self.frame_ans_file_write)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.pushButton_302.setFont(font)
        self.pushButton_302.setObjectName("pushButton_302")
        self.horizontalLayout_ans_file_write.addWidget(self.pushButton_302)
        self.verticalLayout_ans.addWidget(self.frame_ans_file_write)
        self.verticalLayout_left.addWidget(self.frame_ans, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_up.addWidget(self.frame_left, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_right = QtWidgets.QFrame(self.frame_up)
        self.frame_right.setMaximumSize(QtCore.QSize(16777215, 540))
        self.frame_right.setStyleSheet("#frame_right{\n"
"    border: none;\n"
"}\n"
"#frame_view{\n"
"    background: radial-gradient( #E3EFFC 0%, #CDDEFF 100%);\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QTextBrowser {\n"
"    background: #FAFBFE;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_right = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_right.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_right.setSpacing(6)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.frame_view = QtWidgets.QFrame(self.frame_right)
        self.frame_view.setMinimumSize(QtCore.QSize(360, 450))
        self.frame_view.setStyleSheet("#frame_graph{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"#frame_view_set{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"#frame_view_xyz{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QComboBox{\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}")
        self.frame_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view.setObjectName("frame_view")
        self.verticalLayout_view = QtWidgets.QVBoxLayout(self.frame_view)
        self.verticalLayout_view.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_view.setSpacing(0)
        self.verticalLayout_view.setObjectName("verticalLayout_view")
        self.frame_view_set = QtWidgets.QFrame(self.frame_view)
        self.frame_view_set.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_view_set.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_view_set.setStyleSheet("")
        self.frame_view_set.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view_set.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view_set.setObjectName("frame_view_set")
        self.horizontalLayout_view_set = QtWidgets.QHBoxLayout(self.frame_view_set)
        self.horizontalLayout_view_set.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_view_set.setSpacing(6)
        self.horizontalLayout_view_set.setObjectName("horizontalLayout_view_set")
        self.comboBox = QtWidgets.QComboBox(self.frame_view_set)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 24))
        self.comboBox.setMaximumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_view_set.addWidget(self.comboBox)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_view_set.addItem(spacerItem10)
        self.frame_view_xyz = QtWidgets.QFrame(self.frame_view_set)
        self.frame_view_xyz.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255)\n"
"}")
        self.frame_view_xyz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view_xyz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view_xyz.setObjectName("frame_view_xyz")
        self.horizontalLayout_view_xyz = QtWidgets.QHBoxLayout(self.frame_view_xyz)
        self.horizontalLayout_view_xyz.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_view_xyz.setSpacing(2)
        self.horizontalLayout_view_xyz.setObjectName("horizontalLayout_view_xyz")
        self.pushButton_xy = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_xy.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon_xy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_xy.setIcon(icon2)
        self.pushButton_xy.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_xy.setObjectName("pushButton_xy")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_xy)
        self.pushButton_yx = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_yx.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon_yx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_yx.setIcon(icon3)
        self.pushButton_yx.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_yx.setObjectName("pushButton_yx")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_yx)
        self.pushButton_yz = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_yz.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icon_yz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_yz.setIcon(icon4)
        self.pushButton_yz.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_yz.setObjectName("pushButton_yz")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_yz)
        self.pushButton_zy = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_zy.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icon_zy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_zy.setIcon(icon5)
        self.pushButton_zy.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_zy.setObjectName("pushButton_zy")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_zy)
        self.pushButton_zx = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_zx.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icon_zx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_zx.setIcon(icon6)
        self.pushButton_zx.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_zx.setObjectName("pushButton_zx")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_zx)
        self.pushButton_xz = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_xz.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icon_xz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_xz.setIcon(icon7)
        self.pushButton_xz.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_xz.setObjectName("pushButton_xz")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_xz)
        self.horizontalLayout_view_set.addWidget(self.frame_view_xyz)
        self.verticalLayout_view.addWidget(self.frame_view_set)
        self.frame_graph = QtWidgets.QFrame(self.frame_view)
        self.frame_graph.setStyleSheet("")
        self.frame_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph.setObjectName("frame_graph")
        self.verticalLayout_view.addWidget(self.frame_graph)
        self.verticalLayout_right.addWidget(self.frame_view)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(360, 0))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_right.addWidget(self.textBrowser, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_up.addWidget(self.frame_right, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_up, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_down = QtWidgets.QFrame(Dialog)
        self.frame_down.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_down.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_down.setStyleSheet("QPushButton{\n"
"    width: 56px;\n"
"    height: 24px;\n"
"    background: #FFFFFF;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #00337E;\n"
"    font-weight: 600;\n"
"    font-size: 12px;\n"
"    color: #00337E;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}")
        self.frame_down.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_down.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_down.setObjectName("frame_down")
        self.horizontalLayout_down = QtWidgets.QHBoxLayout(self.frame_down)
        self.horizontalLayout_down.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_down.setSpacing(0)
        self.horizontalLayout_down.setObjectName("horizontalLayout_down")
        self.pushButton_0 = QtWidgets.QPushButton(self.frame_down)
        self.pushButton_0.setMaximumSize(QtCore.QSize(56, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")
        self.horizontalLayout_down.addWidget(self.pushButton_0)
        self.verticalLayout.addWidget(self.frame_down, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "小型零件危险位置应力应变辨识"))
        self.label_100.setText(_translate("Dialog", "通过应变片应变辨识（微应变）"))
        self.radioButton.setText(_translate("Dialog", "显示应变片"))
        self.pushButton_11.setText(_translate("Dialog", "S1 y"))
        self.pushButton_12.setText(_translate("Dialog", "S2 y"))
        self.pushButton_13.setText(_translate("Dialog", "S3 z"))
        self.pushButton_14.setText(_translate("Dialog", "S4 x"))
        self.pushButton_15.setText(_translate("Dialog", "S5 x"))
        self.pushButton_16.setText(_translate("Dialog", "S6 z"))
        self.label_101.setText(_translate("Dialog", "从文件读取应变片应变："))
        self.pushButton_101.setText(_translate("Dialog", "选择文件(.xml)"))
        self.pushButton_102.setText(_translate("Dialog", "读取"))
        self.pushButton_103.setText(_translate("Dialog", "清空"))
        self.pushButton_100.setText(_translate("Dialog", "输出"))
        self.label_200.setText(_translate("Dialog", "通过整体受力和力矩辨识"))
        self.label_21.setText(_translate("Dialog", "Fx (N)"))
        self.label_24.setText(_translate("Dialog", "Mx (N·m)"))
        self.label_22.setText(_translate("Dialog", "Fy (N)"))
        self.label_25.setText(_translate("Dialog", "My (N·m)"))
        self.label_23.setText(_translate("Dialog", "Fz (N)"))
        self.label_26.setText(_translate("Dialog", "Mz (N·m)"))
        self.label_201.setText(_translate("Dialog", "从文件读取整体受力和力矩："))
        self.pushButton_201.setText(_translate("Dialog", "选择文件(.xml)"))
        self.pushButton_202.setText(_translate("Dialog", "读取"))
        self.pushButton_203.setText(_translate("Dialog", "清空"))
        self.pushButton_200.setText(_translate("Dialog", "输出"))
        self.label_300.setText(_translate("Dialog", "导出辨识结果"))
        self.label_301.setText(_translate("Dialog", "导出各位置的mises应力："))
        self.pushButton_301.setText(_translate("Dialog", "选择文件夹"))
        self.label_31.setText(_translate("Dialog", "/"))
        self.label_32.setText(_translate("Dialog", ".csv"))
        self.pushButton_302.setText(_translate("Dialog", "导出"))
        self.comboBox.setItemText(0, _translate("Dialog", "网格视图"))
        self.comboBox.setItemText(1, _translate("Dialog", "mises 应力云图"))
        self.pushButton_0.setText(_translate("Dialog", "返回"))
import res_rc
